/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FreshResponse {
  status: number
  headers: Array<Array<string>>
  body: Array<number>
}
export interface FreshRequest {
  url: string
  method: string
  headers: Array<FreshHeader>
}
export interface FreshHeader {
  key: string
  value: Array<number>
}
